"""Add creation_date in Linking database

Revision ID: 1a96b8b9bd83
Revises: 2775f7ed90d2
Create Date: 2025-03-29 23:53:40.031799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a96b8b9bd83'
down_revision: Union[str, None] = '2775f7ed90d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'creation_date')
    # ### end Alembic commands ###
